### ISSUE TITLE
Execution failed for task ':app:processDebugResources'.  Failed to execute aapt

### ISSUE THREAD

**Issue by disooqi** [Kaljurand/K6nele#55]
Hi Kaljurand

I am facing the following error when trying to build K6nele

Caused by: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
        at com.android.builder.png.AaptProcess$NotifierProcessOutput.handleOutput(AaptProcess.java:463)
        at com.android.builder.png.AaptProcess$NotifierProcessOutput.err(AaptProcess.java:415)
        at com.android.builder.png.AaptProcess$ProcessOutputFacade.err(AaptProcess.java:332)
        at com.android.utils.GrabProcessOutput$1.run(GrabProcessOutput.java:104)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 0s
28 actionable tasks: 1 executed, 27 up-to-date

Any suggestion? 
Thanks
Mohamed Eldesouki

**Comment by disooqi** [comment]
Thanks a lot it has built successfully
