### ISSUE TITLE
Crash after pressing Kõnele mic button on TCL/UnionTV Android v8.0.0

### ISSUE THREAD

**Issue by Kaljurand** [Kaljurand/K6nele#73]
Pressing the mic button causes crash. The log shows:

```
java.lang.SecurityException: Not allowed to change Do Not Disturb state
 at android.os.Parcel.readException(Parcel.java:1943)
 at android.os.Parcel.readException(Parcel.java:1889)
 at android.media.IAudioService$Stub$Proxy.setStreamVolume(IAudioService.java:933)
 at android.media.AudioManager.setStreamVolume(AudioManager.java:1010)
 at ee.ioc.phon.android.speechutils.c.a(Unknown Source:41) 
 at ee.ioc.phon.android.speechutils.b.a.onStartListening(Unknown Source:63)
 at android.speech.RecognitionService.dispatchStartListening(RecognitionService.java:113)
 at android.speech.RecognitionService.-wrap3(Unknown Source:0)
 at android.speech.RecognitionService$1.handleMessage(RecognitionService.java:82)
```

Possible solution: https://stackoverflow.com/questions/39151453/in-android-7-api-level-24-my-app-is-not-allowed-to-mute-phone-set-ringer-mode

**Comment by Kaljurand** [comment]
Probably fixed by https://github.com/Kaljurand/K6nele/commit/11e036e270d6e5757033de115fd815fa7b30df81
